transfer_money/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import TransferMoneyView
from .api.router import router
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TransferMoneyView.as_view()),
    path('api/', include(router.urls)),
]

transfer_money/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db import transaction

from .exceptoins import NotEnoughMoney, UsersDoesNotExist


class User(AbstractUser):
    inn = models.TextField(max_length=12, verbose_name="ИНН")
    balance = models.DecimalField(default=Decimal("0.00"), max_digits=6, decimal_places=2, verbose_name="Баланс")

    def transfer_money(self, ammount: Decimal, inn: str):
        users = User.objects.select_for_update().filter(inn=inn)
        with transaction.atomic():
            if self.balance - ammount < 0:
                raise NotEnoughMoney('Not enough money')
            if not users.exists():
                raise UsersDoesNotExist
            self.balance -= ammount
            self.save()
            arrival = ammount / users.count()
            users.update(balance=models.F('balance') + arrival)

transfer_money/forms.py
from django import forms

from .models import User


class TransferMoneyForm(forms.Form):
    users = forms.ModelChoiceField(queryset=User.objects.all(), label='Пользователи')
    inn = forms.CharField(max_length=12, label='ИНН')
    ammount = forms.DecimalField(max_digits=6, decimal_places=2, label='Сумма')

transfer_money/api/views.py
from django.core.exceptions import ValidationError
from django.forms import DecimalField
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response

from .serializers import UserSerializer
from ..exceptoins import NotEnoughMoney, UsersDoesNotExist
from ..models import User


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    authentication_classes = []

    @action(detail=True, methods=['post', ])
    def transfer_money(self, request, pk=None):
        user = self.get_object()
        inn = request.data.get('inn')
        ammount = request.data.get('ammount')
        decimal_field = DecimalField(max_digits=6, decimal_places=2)

        if not (inn or ammount):
            return Response(status=status.HTTP_400_BAD_REQUEST)
        try:
            ammount = decimal_field.clean(ammount)
        except ValidationError:
            return Response(data={'error': 'Неправильная сумма'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            user.transfer_money(inn=inn, ammount=ammount)
        except NotEnoughMoney:
            return Response(data={'error': 'Нехватает денег'}, status=status.HTTP_400_BAD_REQUEST)
        except UsersDoesNotExist:
            return Response(data={'error': 'Пользователи с таким ИНН не найдены'}, status=status.HTTP_400_BAD_REQUEST)
        return Response(status=status.HTTP_200_OK)

transfer_money/views.py
from django.views.generic.edit import FormView

from .forms import TransferMoneyForm


class TransferMoneyView(FormView):
    template_name = 'transfer_money.html'
    form_class = TransferMoneyForm

templates/transfer_money.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <title>Main page</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success">Перевести</button>
</form>
<script>
    $(document).ready(
        $('form').on('submit', (event) => {
            event.preventDefault();
            const id = $('#id_users option:selected').val()
            const inn = $('input[name="inn"]').val()
            const ammount = $('input[name="ammount"]').val()
            $.ajax({
                type: 'POST',
                url: `/api/users/${id}/transfer_money/`,
                data: {inn: inn, ammount: ammount},
                success: () => {
                    alert('Деньги успешно переведены')
                }
            })
                .fail((response) => {
                    alert(response.responseJSON.error)
                })
        })
    )
</script>
</body>
</html>